<?php
/**
 * @file
 * This gets your cloudflare data into JSON format
 */
include 'inc/class_cloudflare.php';
/**
* Implementation of hook_menu().
*/
function dcfapi_menu() {
  //Admin Page
  $items['admin/config/people/dcfapi'] = array(
    'title' => 'Drupal Cloudflare API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dcfapi_admin'),
    'access arguments' => array('administer drupal cloudflare api'),
    'description' => t('Configure the Drupal Cloudflare API settings.')
  );
  //Payload
  $items['dcfapi'] = array(
    'title' => 'Drupal CloudFlare API',
    'page callback' => 'dcfapi_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}
/**
* Implements hook_permission().
*/
function dcfapi_permission() {
  return array(
    'administer drupal cloudflare api' => array(
      'title' => t('Administer Cloudflare API'),
      'description' => t('Perform administration tasks for Cloudflare API.'),
    ),
  );
}
function dcfapi_admin() {
  $form = array();
  $form['dcfapi_email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail address'),
    '#description' => t('Email Address for your CloudFlare account'),
    '#default_value' => variable_get('dcfapi_email', ''),
    '#required' => TRUE,
  );
  $form['dcfapi_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API key'),
    '#description' => t('API key for your Cloudflare account.'),
    '#default_value' => variable_get('dcfapi_key', ''),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function dcfapi_admin_submit($form, &$form_state) {
  $form_values = $form_state['values'];
  variable_set('dcfapi_email', $form_values['api_email']);
  variable_set('dcfapi_key', $form_values['api_key']);
}

function dcfapi_page() {
  $cf_email = variable_get('dcfapi_email', FALSE);
  $cf_api_key = variable_get('dcfapi_key', FALSE);
  $cf = new cloudflare_api($cf_email , $cf_api_key);
  $domains = $cf->zone_load_multi();
  $domain_objs = $domains->response->zones->objs;
  $domain_names = array();
  $response = array();
  //get domain names
  foreach($domain_objs as $domain_obj) {
    $domain_names[] = $domain_obj->zone_name;
  }
  //build json feed
  foreach ($domain_names as $domain_name) {
    $response[$domain_name] = $cf->stats("{$domain_name}", $cf::INTERVAL_24_HOURS);
  }

  print json_encode($response);
}
